### PR TITLE
[FEAT] QD base code additions

### PR DESCRIPTION
**Pull request by kevinl424**
- query decomposition initial code
- only notebooks included

### CODE REVIEW

**Review by seyeong-han — DISMISSED** [review]
Thanks for adding all this previous work!
Could you provide explanations for each file?

**Comment by kevinl424** [comment]
> Thanks for adding all this previous work! Could you provide explanations for each file?

File Breakdown
- langchain_ms.ipynb - using LangChain to breakdown subqueries
- MS_finetuning.ipynb - fine-tuning the query decomposition
- rest - multi step query decomp examples

**Review by seyeong-han — APPROVED** [review]
LGTM
Thanks for your file descriptions.

**Review by kingjulio8238 — APPROVED** [review]
Looks good. Hope to see QD being used once multiprocessing has been integrated!

**Review by seyeong-han — APPROVED** [review]

**Pull request merged**
